### ISSUE TITLE
LuaLanes + LuaSocket

### ISSUE THREAD

**Issue by anfractuosity** [LuaLanes/lanes#107]
I'm trying to spawn a thread for each connection from LuaSocket, using LuaLanes,
I'm currently getting the error 'can't copy non-deep full userdata across lanes'.

(I need to use a separate posix thread for each connection, hence wanting to use LuaLanes, due to needing to perform actual computation on a real core)

Has anyone got any suggestions -- I want to avoid patching either LuaLanes or LuaSocket ideally?

```
lanes = require "lanes".configure{ with_timers = false,protect_allocator = true}
socket = require("socket")

host = host or "*"
port = port or 8030
if arg then
    host = arg[1] or host
    port = arg[2] or port
end

print("Binding to host '" ..host.. "' and port " ..port.. "...")

s = assert(socket.bind(host, port))
i, p   = s:getsockname()
assert(i, p)
print("Waiting connection from talker on " .. i .. ":" .. p .. "...")

function accepter(cv)
    print("Connected. Here is the stuff:")
    l, e = cv:receive()
    while not e do
        print(l)
        l, e = cv:receive()
    end
end

while true do
    c = assert(s:accept())
    m= lanes.gen("*",accepter)
    m(c)
end
```

**Comment by sonoro1234** [comment]
I solved this recreating the connection in the new lanes ( only transfering host and port)

**Comment by Phazeus** [comment]
Can you showhowyou has solve it please?

**Comment by sonoro1234** [comment]
```
https://github.com/sonoro1234/Lua2SC/blob/master/lua2SC/lua/sctcp.lua
```
is for tcp connection and scudp for udp connection.
basically dont send sockets across lanes but only connection data (ip and port)
