### ISSUE TITLE
Alpine Linux(uclibc) + luajit

### ISSUE THREAD

**Issue by DorianGray** [LuaLanes/lanes#116]
It seems that uclibc and it's associated libpthread are missing some symbols so I get fun errors on startup, like...

/usr/bin/luajit: error loading module 'lanes.core' from file '/lib/lanes/core.so':
	Error relocating /lib/lanes/core.so: __pthread_register_cancel: symbol not found
stack traceback:
	[C]: at 0x7fd76af72d31
	[C]: in function 'require'
	/lib/lua/lanes.lua:38: in main chunk
	[C]: in function 'require'
	/lib/lua/init/server.lua:1: in main chunk
	[C]: in function 'require'
	/bin/sh:115: in main chunk
	[C]: at 0x7fd76af36ed9

Is there anything you know of that I can do while building to resolve this? Or will fixing it require code changes?

**Comment by benoit-germain** [comment]
Lanes code doesn't reference any function by the name of pthread_register_cancel. Unfortunately, I'm not pthread-proficient enough to know where this could come from.
