### ISSUE TITLE
Lanes configure fails as user root with luajit

### ISSUE THREAD

**Issue by kallaballa** [LuaLanes/lanes#117]
Initialization of lanes fails as root user _only_. I'm using following code:

<pre>
--test.lua
require "lanes".configure{}
</pre>

and call it like this:

<pre>
luajit test.lua
</pre>

with following result:

<pre>
luajit: (error object is not a string)
</pre>

I found out that the error message indicates that there is an error thrown which isn't convertible to a string, i used pcall to get the error object and i found out that it is userdata with the name "Lanes".

<pre>
local inspect = require("inspect")
s,err = pcall(function()
  require "lanes".configure{}
end)

print(err)
print(inspect(getmetatable(err)))
</pre>

Output:

<pre>
userdata: 0x415eeda8
"Lane"
</pre>

I'm using LuaJIT 2.0.3 on Debian Wheezy.

**Comment by kallaballa** [comment]
btw. im using the current git head

**Comment by benoit-germain** [comment]
That strange, Lanes isn't supposed to throw non-string errors, ever. Maybe there is something going on with LuaJIT. does it also happen with PUC-Lua?
