### ISSUE TITLE
[Idea / Feature] I/O Completion Ports

### ISSUE THREAD

**Issue by andrewstarks** [LuaLanes/lanes#119]
I'm going to play with IOCP in Lua, because they seem to be an excellent fit. As I was planning my approach, it occurred to me that LuaLanes must use mechanisms that are similar, in order to accomplish what it does.

I don't think that you use it, from what I was able to read, but I do think that there would be some nice benefits, if you did. Especially related to being able to interact with OVERLAPPED  I/O objects in Windows. 

FWIW

**Comment by benoit-germain** [comment]
Lanes uses only thread synchonisation facilities. I'm not familiar with overlapped objects, but unless there is some equivalent in pthread or non-windows world, I don't see how Lanes could accomodate them.
