### ISSUE TITLE
LuaRocks: Can't compile

### ISSUE THREAD

**Issue by cmckain14** [LuaLanes/lanes#120]
C:\WINDOWS\system32>luarocks install lanes
Installing https://luarocks.org/lanes-3.10.0-1.rockspec...
Using https://luarocks.org/lanes-3.10.0-1.rockspec... switching to 'build' mode
Cloning into 'lanes'...
remote: Counting objects: 73, done.
remote: Compressing objects: 100% (72/72), done.
remote: Total 73 (delta 3), reused 28 (delta 0), pack-reused 0
Receiving objects: 100% (73/73), 237.00 KiB | 245.00 KiB/s, done.
Resolving deltas: 100% (3/3), done.
Checking connectivity... done.
Note: checking out '295ba159356050037419cbdb5ba1d1e3362ce391'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

mingw32-gcc -O2 -c -o src/compat.o -IC:/Program Files (x86)/Lua/5.2/include/ src
/compat.c -Isrc
mingw32-gcc -O2 -c -o src/deep.o -IC:/Program Files (x86)/Lua/5.2/include/ src/d
eep.c -Isrc
In file included from src/tools.h:8:0,
                 from src/deep.c:36:
src/threading.h:107:19: error: unknown type name 'CONDITION_VARIABLE'
  #define SIGNAL_T CONDITION_VARIABLE
                   ^
src/threading.h:173:19: note: in expansion of macro 'SIGNAL_T'
 void SIGNAL_INIT( SIGNAL_T *ref );
                   ^
src/threading.h:107:19: error: unknown type name 'CONDITION_VARIABLE'
  #define SIGNAL_T CONDITION_VARIABLE
                   ^
src/threading.h:174:19: note: in expansion of macro 'SIGNAL_T'
 void SIGNAL_FREE( SIGNAL_T *ref );
                   ^
src/threading.h:107:19: error: unknown type name 'CONDITION_VARIABLE'
  #define SIGNAL_T CONDITION_VARIABLE
                   ^
src/threading.h:175:18: note: in expansion of macro 'SIGNAL_T'
 void SIGNAL_ALL( SIGNAL_T *ref );
                  ^
src/threading.h:107:19: error: unknown type name 'CONDITION_VARIABLE'
  #define SIGNAL_T CONDITION_VARIABLE
                   ^
src/threading.h:187:21: note: in expansion of macro 'SIGNAL_T'
 bool_t SIGNAL_WAIT( SIGNAL_T *ref, MUTEX_T *mu, time_d timeout );
                     ^

Error: Build error: Failed compiling object src/deep.o

C:\WINDOWS\system32>

**Comment by UKnowMe** [comment]
Can confirm that it happens with MinGW under Windows. Probably because MinGW is shipped with pthreads but due to some version constants lanes expects the Windows Threading Libraries.

**Comment by lucidBrot** [comment]
compilation still fails in 2020 with
```echo -llua | xargs gcc -O2 -fPIC -I/usr/include -c src/threading.c -o src/threading.o -Isrc
src/threading.c: In function ‘THREAD_CREATE’:
src/threading.c:812:45: error: ‘_PRIO_MODE’ undeclared (first use in this function)
  812 |   PT_CALL( pthread_attr_setschedpolicy( &a, _PRIO_MODE));
      |                                             ^~~~~~~~~~
```
in cygwin.  

I used `luarocks install lanes` with luarocks version 3.3.1

**Comment by abreulima** [comment]
I think it's a problem with a version of Lua. I had the same problem and I used a different version 
I used https://github.com/luarocks/hererocks to use a different version.
