### ISSUE TITLE
Old programmer, new to Lanes, documentation update suggestion

### ISSUE THREAD

**Issue by cpeosphoros** [LuaLanes/lanes#130]
Not a bug, but a feature which took me about 5 work hours to figure out.

I'm trying to adapt an existing codebase to use Lanes as a multithreading framework.

First step I took (after studying Lanes' API, having small test cases working, etc) was encapsulate all the processing of the current code into a single function `work() `and then run it through a single lane.

It's an io/networking intensive process, that currently takes about 2 hours to run in a top linux machine. Hence the need for true multithreading.

The process started quite well, work was done, all right. Then, with no apparent cause (at least to me), the lane self destructed, got garbage collected and the application stopped, returning to OS prompt.

It worked fine, through the end, when provided with a very small data sample as input.

Logging showed it happened in the middle of processing. Sometimes in the middle of a for or a while true loop. Profiling shows it happened between 0.25 to 0.28 seconds after the application started.

After a lot of searching and guessing, I figured out that there was nothing keeping the application alive while the lane was running and the approximately 0.25 secs timing was from shutdown_timeout.

Now, I have about 25 years experience as a programmer, 2 years with Lua, and have built a massive Java multi threading application in the banking industry, amongst lots of other projects. I'm not saying that to brag, but to point out that the documentation as is may be misleading to newcomers. 

None of the information on http://lualanes.github.io/lanes explicitly points that the application must be kept alive while the lanes are running. Certainly there are lots of hints out there - and I ended figuring it out from them, but no open statement to that feature.

For most of the time, I thought the fault was on my side - as I had a lot of fun troubles figuring out how to manage the right placement foor upvalues, userdata, C libraries, etc. I just thought it was one more problem with my legacy code.

So, my suggestion is to write it down in the documentation that the application must be kept alive while the lanes are running.

As a side note, just FYI, passing the whole processing work through a single lane over about 15 full trial runs added an average 0.7 seconds overhead.

Anyways, great framework, great job you guys. Way simpler than trying to do the same thing with Java.

Lanes works like magic, thank you.

**Comment by benoit-germain** [comment]
Well,

I'm glad Lanes works for you :).

Now, regarding the fact that the application must be kept alive, I admit that it seemed so obvious I didn't even think about mentioning it. But Lanes creates threads, not processes, therefore these will terminate when the application ends. But I agree, more documentation never hurts.

**Comment by benoit-germain** [comment]
2d8bd5f3b7f573fffa7f1b5f691b7dbde0c1805b adds a line about it in the Limitations section at the beginning of the documentation.
