### ISSUE TITLE
problems with DeepUserData

### ISSUE THREAD

**Issue by jjvbsag** [LuaLanes/lanes#131]
Despite of the mininal documentation I managed to prepare one of my C data structs to be passed from one thread to another using linda.

BUT: Now I cannot use the module without linda any more...

```lua
local lanes = require"lanes".configure()
local linda = lanes.linda()
require"MYMODULE"
local data=MYMODULE.getdata()
:::
```
runs fine, but using MYMODULE without linda
```lua
require"MYMODULE"
local data=MYMODULE.getdata()
:::
```
gives a SEGV before getdata() returns.

Is this a known bug/feature or any way to prevent crashing?

I really need MYMODULE in a single thread _and_ in a multithread environment. Please give any advice...

---
Developing on Xubuntu 16.04, target system is IMX6UL (arm7vl linux)

**Comment by benoit-germain** [comment]
Hm. As a matter of fact I haven't tried :). I'll have to test this myself. A bug in Lanes isn't out of the question.

**Comment by benoit-germain** [comment]
Work is in progress to solve that issue. Shouldn't be too long now. A bit more complex than I expected though :)

**Comment by jjvbsag** [comment]
@benoit-germain : thats great. I'm quite busy on the job, but when I find the time, I'll try to reduce my problematic module to a minimalistic sample, which then
- can be used by you to verify your solution
- could be added to lanes as a sample to give others a better starting point...

**Comment by benoit-germain** [comment]
I had to make a minimal module to test my changes anyway

**Comment by jjvbsag** [comment]
Ok. Looking forward for the next release. And Thanks! :+1:

**Comment by benoit-germain** [comment]
Should be taken care of by e0dbd33c2d4776d6b2213dd82f344166eafde438. Notice that your module must compile deep.c and universe.c now.

**Comment by jjvbsag** [comment]
@benoit-germain Ok, I'll start testing. Some first results:

**deep_test.c wont compile** with lua5.1 because ```luaL_setfuncs``` is introduced with lua5.2. You should add a back compatibility replacement.
Because I compile on linux with gcc and -Wall -Werror, I had to add several missing includes. I can send you a diff, if you are interested. ¹)

**deep_test.lua also gives problems**.
```l.put( "key", deep)``` results in _```attempt to call field 'put' (a nil value)```_
```local out = l.get( "key")``` results in _```bad argument #1 to 'get' (expecting a linda object)```_
I changed the lines to
```lua
l:set( "key", deep)
local out = l:get( "key")
```
and the script runs fine. Did the script work at your place? How? What is your testing/development system?

I will now continue with my own classes. Coming back soon :beer:

¹) Because proxy difficulties at my workplace and lack of time, I cannot do a pull request for now. Maybe I will try lateron.

**Comment by benoit-germain** [comment]
The test script is pretty much work in progress :).

**Comment by jjvbsag** [comment]
@benoit-germain I can see, you are still working on it! :smiley: 

One more question: Your test scripts currently reads:
```lua
local deep = dt.new_deep()
deep:set(666)
```
Q: How would you implement passing data to the constructor?
```lua
local deep = dt.new_deep(666)
```
My solution for now is the following:
```c
static int lua_pushcomplex(lua_State*L,const S_COMPLEX&complex)
{
	luaG_newdeepuserdata(L,complex_id);
	S_COMPLEX*pComplex=lua_checkcomplex(L,-1);
	*pComplex=complex;
	return 1;
}

static int lua_complex_new(lua_State*L)
{
	S_COMPLEX complex;
	complex.re=luaL_checknumber(L,1);
	complex.im=luaL_checknumber(L,2);
	return lua_pushcomplex(L,complex);
}
```
(I need ```lua_pushcomplex(L,complex);``` at several places to push results of operations onto the stack)
What do you think about this? Any suggestions/improvements?

**Comment by benoit-germain** [comment]
This complex stuff makes me think about something: your complex is a full userdata because you need a metatable. However, implementing it as a deep userdata means that when you send a complex value in a lane for some computations, the complex object is shared between the sender and the receiver, with all multithreading issues it implies.
I think that what you need is a non-deep userdata that could be copied over by value. I think that I could implement the detection of a "__clone" member in the metatable that you could provide.

**Comment by jjvbsag** [comment]
> the complex object is shared between the sender and the receiver, with all multithreading issues it implies.

This is no problem for me, because S_COMPLEX is implements as a real first-class value. It's _never_ modified, instead on operations a new instance with the resulting value is created:

```c
static int lua_complex_add(lua_State*L)
{
	const S_COMPLEX*a=lua_checkcomplex(L,1);
	const S_COMPLEX*b=lua_checkcomplex(L,2);
	S_COMPLEX sum= {a->re+b->re,a->im+b->im};
	return lua_pushcomplex(L,sum);
}
```

But thank you for pointing this out. You should mention it, when you update your documentation. 

BTW: My lcomplex.cpp is still work-in-progress, I will happily share it, when done...

**Comment by jjvbsag** [comment]
> BTW: My lcomplex.cpp is still work-in-progress, I will happily share it, when done...

Just for completeness: lcomplex.cpp can now be found at [COMPLEX](https://github.com/jjvbsag/COMPLEX)

**Comment by benoit-germain** [comment]
I guess I can close that one as #137 more or less takes over from here.

**Comment by jjvbsag** [comment]
Your guess is right. Thanks for all the efforts. :beer:
