### ISSUE TITLE
Error launching the program

### ISSUE THREAD

**Issue by Yupppi** [LuaLanes/lanes#132]
I get following warning on windows 7 with installer and non-installer versions from TASvideos. Any help? I tried installing bizhawk pre-requisites for bsnes core. I also got a working lsnes directory from a friend but that gave the same error.
![lsnes_error](https://user-images.githubusercontent.com/24705202/28801080-8467253c-7658-11e7-8934-1f5d5971ccfc.PNG)

**Comment by benoit-germain** [comment]
Sorry, but I don't understand what it has to do with Lanes. Are you sure this is the right place for your issue?

**Comment by Yupppi** [comment]
I'm sorry, I had a different page open but had to log in and it apparently threw me into wrong github. Sorry about that.
