### ISSUE TITLE
Using luasqlite3 with lanes

### ISSUE THREAD

**Issue by Aditya23456** [LuaLanes/lanes#134]
Hi,

I am developing a multithreading application with lua lanes. Each thread makes a database connection and updates it own table from same database . I can consequently read from all 3 threads but only one of my thread can write to the database and any other thread show dB is locked error. I read the reason behind this is using same dB connection between threads but I'm not doing it. When I print environment object I see different data structure object. It would be great if anyone who worked with lua lanes and sqllite library can suggest where I'm doing it wrong.

Thanks,
Aditya

**Comment by sonoro1234** [comment]
I have not used luasqlite3 but it does not seem lanes issue but luasqlite3 issue. Are you able to open and write to the three connections from one simple script without lanes? (Perhaps leaving one opened)

**Comment by benoit-germain** [comment]
I don't know how sqllite is supposed to work, but IMHO, preventing read access while a write is in progress seems pretty logical to me, as you don't want the reads to pull data while they are being updated, which can end up in any kind of bad result you can think of.
