### ISSUE TITLE
LuaJIT + lanes huge memory leak

### ISSUE THREAD

**Issue by valid-ptr** [LuaLanes/lanes#141]
This example works without any leaks on the vanilla lua5.1:
```

local lanes = require "lanes.lua"
lanes.configure({protect_allocator=true})

for i=1,100000 do
	print("i = " .. i)

	-- Leaking
	local lane = lanes.gen("*", { globals = {} }, function() print("lane done = " .. i) end)()
--	local lane = lanes.gen("lanes.core",
--						   { globals = {} }, function() print("lane done = " .. i) end)()

	-- No Leak (without lanes.core)
--	local lane = lanes.gen("package,table,io,os,string,math,debug,base,coroutine",
--						   { globals = {} }, function() print("lane done = " .. i) end)()

	lane:join()
	collectgarbage()
	print("Lua mem usage: " .. collectgarbage("count")*1024)
end

--[[
Test failed with
LuaJIT-2.0.5, LuaJIT-2.1.0-beta3
luajit in the top takes about 1GB

Result:
lane done = 15670
Lua mem usage: 64314
i = 15671
/usr/bin/luajit: lanes_stress.lua:7: luaG_newstate() failed while creating state; out of memory
stack traceback:
    [C]: at 0x7f908d022d0d
    lanes_stress.lua:7: in main chunk
    [C]: at 0x00404cb0
--]]

```

**Comment by sonoro1234** [comment]
Not happening with
https://github.com/LuaLanes/lanes/commit/fcd08030b6b6af81a8aa2672082a55f602006f78
(I am not able to compile after this commit)

**Comment by sonoro1234** [comment]
Also tried after PR that solves #143 and problem dont appears

**Comment by sonoro1234** [comment]
protect_allocator=false 
gives a crash

**Comment by sonoro1234** [comment]
@valid-ptr in which OS are you running script?

**Comment by valid-ptr** [comment]
Linux Slackware64 14.2

Linux zorro 4.4.132 #2 SMP Mon May 21 17:38:57 CDT 2018 x86_64 Intel(R) Core(TM) i7 CPU         860  @ 2.80GHz GenuineIntel GNU/Linux

**Comment by sonoro1234** [comment]
So there are two differences from my test. 
I am on windows and compiling for 32 bits

Are you able to try 32bits?

**Comment by valid-ptr** [comment]
I've tested lanes-3.11 release on x86_64 only.
I'll check master + PR #143 today

I am not able to test on x86 right now.

**Comment by valid-ptr** [comment]
mater + PR #143  on luajit gives this error:
```

root@zorro:~/tmp/lua_lanes_tests# /opt/EVI/linux-x86_64/bin/luajit-2.1.0-beta3 lanes_stress.lua
/opt/EVI/linux-x86_64/bin/luajit-2.1.0-beta3: bad light userdata pointer
stack traceback:
    [C]: in function 'configure'
    ./lanes/lua.lua:132: in function 'configure'
    lanes_stress.lua:2: in main chunk
    [C]: at 0x00404cb0

```

Clean master (without PR #143) can't be compiled with luajit-2.1.0-beta3:
```

/root/build/lanes/src/deep.c:273:13: error: conflicting types for ‘push_deep_proxy’
 char const* push_deep_proxy( struct s_Universe* U, lua_State* L, struct DEEP_PRELUDE* prelude, enum eLookupMode mode_)
             ^
In file included from /root/build/lanes/src/deep.c:36:0:
/root/build/lanes/src/tools.h:48:13: note: previous declaration of ‘push_deep_proxy’ was here
 char const* push_deep_proxy( struct s_Universe* U, lua_State* L, struct DEEP_PRELUDE* prelude, enum eLookupMode mode_);
             ^
CMakeFiles/core.dir/build.make:86: recipe for target 'CMakeFiles/core.dir/src/deep.c.o' failed

```

**Comment by sonoro1234** [comment]
Is lanes.lua from the last master?

**Comment by valid-ptr** [comment]
Yes

**Comment by sonoro1234** [comment]
It could be a LuaJIT limitation
see 
https://www.freelists.org/post/luajit/Panic-when-building-the-lua-bindings-for-the-enlightenment-foundation-libraries-efl-on-aarch64,1

https://github.com/hexchat/hexchat/issues/2116

Althought this limitation is not for all 64bit systems

**Comment by benoit-germain** [comment]
Lanes uses lightuserdata in various places as table keys, as it is the fastest and easiest way to generate some unique keys with said light userdata taking the value of some C function pointer. But then this pointer isn't used to call the function, it's just some unique value. Not sure what it has to do with your issue...

**Comment by sonoro1234** [comment]
It has no relation to #143 but to one issue appeared in this thread
see: https://github.com/LuaLanes/lanes/issues/141#issuecomment-432211944

I have a plan to solve it by replacing push_lightuserdata with another function when compiling with LuaJIT 64 bits but as I need #143 solved to proceed I will wait until you commit something solving #143

**Comment by sonoro1234** [comment]
The issue is present also with the version in PR  #149 with LuaJIT x86_64 (also tested with LUAJIT_ENABLE_GC64)
The system memory monitor shows how memory is consumed and never released!!

**Comment by valid-ptr** [comment]
Right!
But there is no leak and no crash with protect_allocator=false under Linux x86_64 (using this code sample above).

(Latest lanes release 3.11 + LuaJit-2.1.0-beta3)

PS
[Allocator-thread-safety-question (2014)](https://www.freelists.org/post/luajit/Allocator-thread-safety-question,1)
What about this thread?

**Comment by benoit-germain** [comment]
All that lanes does with protect_allocator is this:
```
	lua_getfield( L, 1, "protect_allocator");                                            // settings protect_allocator
	if( lua_toboolean( L, -1))
	{
		void* allocUD;
		lua_Alloc allocF = lua_getallocf( L, &allocUD);
		if( allocF != protected_lua_Alloc) // just in case
		{
			struct ProtectedAllocator_s* s = (struct ProtectedAllocator_s*) allocF( allocUD, NULL, 0, sizeof( struct ProtectedAllocator_s));
			s->allocF = allocF;
			s->allocUD = allocUD;
			MUTEX_INIT( &s->lock);
			lua_setallocf( L, protected_lua_Alloc, s);
		}
	}
	lua_pop( L, 1);                                                                      // settings
```

In other words, call the allocator I find, with a mutex around it.

**Comment by sonoro1234** [comment]
I was not talking about how it works.
In my investigation of the memory leak I found that protect_allocator should be set acording to this

ffi.abi("64bit") true and ffi.abi"gc64" false -> protect_allocator=false
ffi.abi("64bit") true and ffi.abi"gc64" true -> protect_allocator=true
ffi.abi("32bit") true -> protect_allocator=true

And all works as a charm.

ffi.abi is the LuaJIT function that gives information about the LuaJIT compiled, it should be called from lanes.lua (not possible from C API) and provide the default protect_allocator value

**Comment by valid-ptr** [comment]
> All that lanes does with protect_allocator is this:
> 
> ```
> /*
> ** mutex-protected allocator for use with Lua states that have non-threadsafe allocators (such as LuaJIT)
> */
> struct ProtectedAllocator_s
> {
> 	lua_Alloc allocF;
> 	void* allocUD;
> 	MUTEX_T lock;
> };
> void * protected_lua_Alloc( void *ud, void *ptr, size_t osize, size_t nsize)
> {
> 	void* p;
> 	struct ProtectedAllocator_s* s = (struct ProtectedAllocator_s*) ud;
> 	MUTEX_LOCK( &s->lock);
> 	p = s->allocF( s->allocUD, ptr, osize, nsize);
> 	MUTEX_UNLOCK( &s->lock);
> 	return p;
> }
> 
> ...
> 
> 
> 	lua_getfield( L, 1, "protect_allocator");                                            // settings protect_allocator
> 	if( lua_toboolean( L, -1))
> 	{
> 		void* allocUD;
> 		lua_Alloc allocF = lua_getallocf( L, &allocUD);
> 		if( allocF != protected_lua_Alloc) // just in case
> 		{
> 			struct ProtectedAllocator_s* s = (struct ProtectedAllocator_s*) allocF( allocUD, NULL, 0, sizeof( struct ProtectedAllocator_s));
> 			s->allocF = allocF;
> 			s->allocUD = allocUD;
> 			MUTEX_INIT( &s->lock);
> 			lua_setallocf( L, protected_lua_Alloc, s);
> 		}
> 	}
> 	lua_pop( L, 1);                                                                      // settings
> ```
> 
> In other words, call the allocator I find, with a mutex around it.

It can be a bug in LuaJIT (allocator or something else like lua_setallocf function etc.), but Mike Pall closed this issue
https://github.com/LuaJIT/LuaJIT/issues/443

**Comment by benoit-germain** [comment]
Basically I think that the (now inexistent) allocator propagation and ``protect_allocator`` option both don't combine well with LuaJIT. All this changed with 8d6500fe389624be422ee546f71a1efd4456eabe. Just leave the new ``allocator`` option empty and all should be well.
