### ISSUE TITLE
protectproxy.lua fails

### ISSUE THREAD

**Issue by sonoro1234** [LuaLanes/lanes#145]
C:\luaGL\luajit.exe: C:\luaGL\lua\lanes.lua:114: Bad parameter #1 to lanes.configure(), should be a table
stack traceback:
        [C]: in function 'error'
        C:\luaGL\lua\lanes.lua:114: in function 'params_checker'
        C:\luaGL\lua\lanes.lua:132: in function 'configure'
        ...es\build_lanes\install\share\lanes\test\protectproxy.lua:2: in main chunk
        [C]: at 0x00402130

**Comment by benoit-germain** [comment]
Fixed by 5cb15be26174d3aa0dca2699a03baabefa147264
