### ISSUE TITLE
package.loaded.ffi is nil

### ISSUE THREAD

**Issue by sonoro1234** [LuaLanes/lanes#155]
So that protect_allocator default value is not properly set
Just saw docs modification. Seems that user is required to load ffi before lanes to properly detect?

**Comment by benoit-germain** [comment]
Yes. I don't want Lanes to require ffi by itself as it is not necessarily what the user wants. So either the user knows what (s)he doing and has to manually set protect_allocator to true or false, or leaves Lanes in autodetection mode and should require ffi for that beforehand

**Comment by sonoro1234** [comment]
How is that jit and bit are opened but ffi is not?
Where is this happening?

**Comment by benoit-germain** [comment]
It seems to be the normal LuaJIT behavior

```
=== Successfully built LuaJIT for Windows/x64 ===

C:\Lua\LuaJIT-2.0.5\src>luajit
LuaJIT 2.0.5 -- Copyright (C) 2005-2017 Mike Pall. http://luajit.org/
JIT: ON CMOV SSE2 SSE3 SSE4.1 fold cse dce fwd dse narrow loop abc sink fuse
> =ffi
nil
> =package.loaded.fii
nil
> =package.loaded.ffi
nil
> require "ffi"
> =package.loaded.ffi
table: 0x11b5a520
>
```

**Comment by sonoro1234** [comment]
Ahh, I see.
