### ISSUE TITLE
require"ffi"

### ISSUE THREAD

**Issue by sonoro1234** [LuaLanes/lanes#160]
When using lanes from LuaJIT
```
if jit then require"ffi" end
```
must be used before require"lanes" or it will crash in 32bits not getting protect_allocator.

I think it would be cleaner if it is done in lanes.lua

The only caveat is that there are LuaJIT builds without ffi
Just made question in https://github.com/LuaJIT/LuaJIT/issues/457

**Comment by benoit-germain** [comment]
I still think that since Lanes doesn't actually *need* jit, it should not require it.

**Comment by benoit-germain** [comment]
No longer relevant with 8d6500fe389624be422ee546f71a1efd4456eabe.
