### ISSUE TITLE
CPU_ZERO is undefined

### ISSUE THREAD

**Issue by jjvbsag** [LuaLanes/lanes#162]
message when compiling for arm and testing on an ARM board
```
luajit: error loading module 'lanes.core' from file '/usr/local/lib/lua/5.1/lanes/core.so':
        /usr/local/lib/lua/5.1/lanes/core.so: undefined symbol: CPU_ZERO
```
am I missing a library?

**Comment by benoit-germain** [comment]
No this is a macro, defined in <shed.h>.

**Comment by jjvbsag** [comment]
@benoit-germain  Ok, found the problem. Because Lanes is'n really targeted for _crosscompiling_, we had to tweak the Makefiles. And I missed to add `-D_GNU_SOURCE` to `CFLAGS`
