### ISSUE TITLE
does linda objects with __lanesclone work from thread to thread?

### ISSUE THREAD

**Issue by jjvbsag** [LuaLanes/lanes#163]
I took the following script (taken from [lindas documentation](https://lualanes.github.io/lanes/#lindas) ) and modified just a little (io.flush and only 10, not 10000).
```lua
local lanes=require "lanes".configure()
local linda = lanes.linda()
local function loop( max)
	for i = 1, max do
		print( "sending: " .. i)io.flush()
		linda:send( "x", i)    -- linda as upvalue
	end
end

a = lanes.gen( "*", loop)(10)
while true do
	local key, val = linda:receive( 3.0, "x")    -- timeout in seconds
	if val == nil then
		print( "timed out")io.flush()
		break
	end
	print( tostring( linda) .. " received: " .. val)io.flush()
end
```
and get the (expected) output
```
>lua5.1 "simple-linda.lua"
sending: 1
sending: 2
sending: 3
Linda: 0x9bfab0 received: 1
sending: 4
Linda: 0x9bfab0 received: 2
sending: 5
Linda: 0x9bfab0 received: 3
sending: 6
sending: 7
sending: 8
Linda: 0x9bfab0 received: 4
Linda: 0x9bfab0 received: 5
sending: 9
sending: 10
Linda: 0x9bfab0 received: 6
Linda: 0x9bfab0 received: 7
Linda: 0x9bfab0 received: 8
Linda: 0x9bfab0 received: 9
Linda: 0x9bfab0 received: 10
timed out
>Exit code: 0
```

Then I adapted it to test [COMPLEX](https://github.com/jjvbsag/COMPLEX) : 

```lua
local COMPLEX=require"COMPLEX"
local lanes=require "lanes".configure()
local linda = lanes.linda()
local function loop( max)
	for i = 1, max do
		print( "sending: " .. i)io.flush()
		linda:send( "x", COMPLEX.new(i,i))    -- linda as upvalue
	end
end

a = lanes.gen( "*", loop)(10)
while true do
	local key, val = linda:receive( 3.0, "x")    -- timeout in seconds
	if val == nil then
		print( "timed out")io.flush()
		break
	end
	print( tostring( linda) .. " received: " .. tostring(val))io.flush()
end
```
Then I get
```
lua5.1: ./lanes.lua:332: main: function 'COMPLEX/__COMPLEX-27A6AB09-6B67-4D08-BF4C-E054141C07DCMT/__lanesclone' not found in Lane #0x1a5c320 destination transfer database.
```

I changed the script to
```lua
local COMPLEX=require"COMPLEX"
local lanes=require "lanes".configure()
local linda = lanes.linda()
local function loop( max)
	local COMPLEX=require"COMPLEX"
	for i = 1, max do
		print( "sending: " .. i)io.flush()
		linda:send( "x", COMPLEX.new(i,i))    -- linda as upvalue
	end
end

a = lanes.gen( "*", loop)(10)
while true do
	local key, val = linda:receive( 3.0, "x")    -- timeout in seconds
	if val == nil then
		print( "timed out")io.flush()
		break
	end
	print( tostring( linda) .. " received: " .. tostring(val))io.flush()
end
```

then I get
```
>lua5.1 "simple-linda-complex.lua"
sending: 1
timed out
>Exit code: 0
```

:sos: HELP NEEDED :sos:

Am I missing something? Which is the correct way to use __lanesclone over lanes threads?

**Comment by benoit-germain** [comment]
Looks like a bug on my side

**Comment by benoit-germain** [comment]
Pending my solving of a Lanes issue I don't quite have  the time to tackle just now, this should work for you:
```lua
local lanes=require "lanes".configure()
local COMPLEX=lanes.require"COMPLEX"

local linda = lanes.linda()

local function loop( max)
	local lanes=require "lanes"
	local COMPLEX=lanes.require"COMPLEX"
	for i = 1, max do
		print( "sending: " .. i)io.flush()
		linda:send( "x", COMPLEX.new(i,i))    -- linda as upvalue
	end
end

a = lanes.gen( "*", loop)(10)
a:join()
while true do
	local key, val = linda:receive( 3.0, "x")    -- timeout in seconds
	if val == nil then
		print( "timed out")io.flush()
		break
	end
	print( tostring( linda) .. " received: " .. tostring(val))io.flush()
end
 ```

**Comment by jjvbsag** [comment]
:+1: Confirmed :+1: thank you.

**Comment by jjvbsag** [comment]
:beer: :tulip: :rose:  Just to give you a feedback, it also works on the embedded ARM platform :+1: 

:cloud_with_rain: The only problem is, after the script is finished, I get a `segmentation fault`.

This is even true for the two liner
```lua
local lanes=require "lanes".configure()
local linda=lanes.linda()
```

---

This is on an "ARMv7" system with a "Freescale i.MX6 UltraLite", kernel is linux-4.9, lua is LuaJIT 2.0.5

**Comment by jjvbsag** [comment]
@benoit-germain Sorry to say that, but also with the update I get a Segmentation fault for
```sh
luajit -e'require"lanes".configure()'
```

**Comment by benoit-germain** [comment]
I get the crash too. I have a full userdata (let's call it U) in the main LuaJIT state that is created during the configure() call (call that one L). This userdata has a __gc metamethod called when the program closes and the main LuaJIT state is cleaned up. The crash happens in there. Among other things, this metamethod calls ``lua_close()`` on ANOTHER Lua state (the keeper state used to hold transiting linda data, let's call it K). And for some reason calling ``lua_close(K)`` inside ``U.__gc`` frees the memory of U, which is a userdata of L! How is it ever possible?
I'm not sure if this is a LuaJIT bug, but this is really strange, as I don't observe this with PUC-Lua...

**Comment by jjvbsag** [comment]
@benoit-germain Just a hypothetical question: As the - lets call it _clonable_ - userdata with `__lanesclone` now is functional: Is there any need for deep_userdata any more? I don´t really have a deep insight in lanes/linda, but for my target project I'm complete happy with __lanesclone for now. And it's more easy to implement without much overhead.

**Comment by benoit-germain** [comment]
Yes. Typically, a linda is a deep userdata because it contains non-clonable stuff, so the underlying implementation must work on the very same object in every lane that references it. A clone won't do.
In theory, I could indeed make a linda clonable, and have the linda implementation handle cloning in the way it chooses. Deep userdata just offers a generic mechanism for that, and linda is just a deep userdata like any other as far a Lanes is concerned.

**Comment by benoit-germain** [comment]
Did another test by disabling PROPAGATE_ALLOCF and the crash is gone. I wonder if LuaJIT has some internal assumption a given Lua state comes with an allocator that should never be used by another state, and counts on that.

**Comment by jjvbsag** [comment]
@benoit-germain just a confirmation for you: with the latest commits
```lua
luajit -e'require"lanes".configure()'
``` 
also works without segfault on the arm system. Thanks for all your efforts :candy: :cake: :cocktail: 

Regards
