### ISSUE TITLE
lane:cancel question

### ISSUE THREAD

**Issue by sonoro1234** [LuaLanes/lanes#174]
Can the lane be cancelled by lane:cancel (I know it can be killed or hard cancelled with force_kill_bool=true) if this lane is running an endles loop (a script error) without calls to linda send or receive?

**Comment by benoit-germain** [comment]
Yes it can if you configure it with a cancelstep. see [lane creation](http://lualanes.github.io/lanes/#creation). Of course since it uses the line hook expect a performance hit.

**Comment by sonoro1234** [comment]
It returns with timeout after 1 sec (with cancelstep==100)

**Comment by benoit-germain** [comment]
Well, there is a cancelstep unit test in basic.lua (lines 115 to 149). As far as I can tell the test passes so the feature looks like it works. Is there anything different in your case?

**Comment by sonoro1234** [comment]
Yes, it works. I will have to check my program.

**Comment by sonoro1234** [comment]
If in the test I do `print("cance lresult",lane9:cancel())` instead of `lane9:cancel()` the printing is `cancel result    false   timeout` and this is what happens in my program where I dont wait for the status.
Is this behaviour ok?

**Comment by benoit-germain** [comment]
Yes this is the expected behavior. timeout in that case means that the lane hasn't processed the cancel request yet (it will do so when the line hook counter elapses). Which makes me think of a potential optimization: instead of installing the cancel line hook immediately, do so only when calling lanes.cancel.

**Comment by sonoro1234** [comment]
If I replace `local task_launch2= lanes.gen( "", { cancelstep=100, globals={hey=true}, gc_cb = gc_cb}, task )` with `local task_launch2= lanes.gen( "*", { cancelstep=100, globals={hey=true}, gc_cb = gc_cb}, task )`
cancel is failing

**Comment by benoit-germain** [comment]
I have extracted the cancel tests from basic.lua locally for test purposes and I don't see any difference between the two variants.

**Comment by sonoro1234** [comment]
Did the same with this
```
lanes = require"lanes".configure{ with_timers = false}

local function task( a, b, c )
    set_debug_threadname( "task("..a..","..b..","..c..")")
    assert(hey)
    local v=0
	while true do
	end
    return v, hey
end
local task_launch2= lanes.gen( "*", { cancelstep=100, globals={hey=true}, gc_cb = gc_cb}, task )

local N=math.huge --999999999
local lane9= task_launch2(1,N,1)   -- huuuuuuge...

local st
local t0= os.time()
while os.time()-t0 < 5 do
    st= lane9.status
    io.stderr:write( (i==1) and st.." " or '.' )
    if st~="pending" then break end
end
print(" "..st)

if st=="error" then
    local _= lane9[0]  -- propagate the error here
end
if st=="done" then
    error( "Looping to "..N.." was not long enough (cannot test cancellation)" )
end
assert( st=="running" )

lane9:cancel()

local t0= os.time()
while os.time()-t0 < 5 do
    st= lane9.status
    io.stderr:write( (i==1) and st.." " or '.' )
    if st~="running" then break end
end
print(" "..st,os.time()-t0)

io.read"*l"

```
and got differences

**Comment by benoit-germain** [comment]
No difference for me:
```
D:\Boulot\anubis\Lua\bindings\Lanes\lanes\tests>D:\Boulot\anubis\Lua\framework\lua53 cancelstep.lua
............................ running
.. cancelled    0


D:\Boulot\anubis\Lua\bindings\Lanes\lanes\tests>D:\Boulot\anubis\Lua\framework\lua53 cancelstep.lua
........................... running
.. cancelled    0

```

**Comment by sonoro1234** [comment]
With luajit?

**Comment by benoit-germain** [comment]
no, PUC-Lua 5.3.5.

**Comment by sonoro1234** [comment]
Could you try with LuaJIT?

**Comment by benoit-germain** [comment]
I think this is due to code JITting. if the JIT compiler can fully compile the code, then the hook will never be called and the lane won't ever cancel itself.
Take this lane body:
```lua
local function task()
    set_finalizer(function(err, stk) 
        print("finalizer1",err)
    end)
    set_debug_threadname( "task")
    assert(hey)
	print 'start task loop'
    local v=0
	while true do
		v = v + 1
		-- if cancel_test() then
		-- 	print 'aware of cancel request'
		-- end
	end
    return v, hey
end
```
The lane will cancel properly if you uncomment the additional bit of code.
I don't know why this happens only when the lane uses "*". Maybe this enables JIT compiling for the lane instead of being limited to interpreter mode, in which case hooks are called regardless of code complexity.

**Comment by sonoro1234** [comment]
Yes, I have checked that setting `jit.off(true, true)` inside task cancel succeds!!

This is quite inconvenient as it does not make sense to use LuaJIT and turn jit off.
Also cancel_test is no solution because what I need is to cancel any script which is bad written and trapped in a loop (so it wont have cancel_step)

**Comment by benoit-germain** [comment]
Not sure I can do much about that. Any sandbox running untrusted code has the same problem, Lanes or no.
Currently Lanes installs the instructions hook (not the line hook as the documentation states). I plan to be able to make the API offer the choice. Maybe this will help?

**Comment by sonoro1234** [comment]
Sorry, I dont have enough knowledge to answer.

**Comment by benoit-germain** [comment]
I've changed a bit the cancellation stuff in 9c84074c89661cd1e776eff3d4aa5329a2ac9524. It doesn't change anything about those sandboxing issues, but then that wasn't the point. Feel free to report any issue.
