### ISSUE TITLE
Bad light usedata pointer LuaJIT 64 bits again

### ISSUE THREAD

**Issue by sonoro1234** [LuaLanes/lanes#175]
local lanes = require"lanes"

returns
```
C:\supercolliderrepos\aaabuildlua2sctest64\install\luajit.exe: bad light userdata pointer
stack traceback:
        [C]: at 0x618c44d0
        [C]: in function 'require'
        ...colliderrepos\aaabuildlua2sctest64\install\lua\lanes.lua:38: in main chunk
        [C]: in function 'require'
        C:\Lua2SCinstalled\test.lua:1: in main chunk
        [C]: at 0x00402070
```
I cant bisect properly because all happened when CMakeList was temporaly broken (I can only build with cmake) But it should be around commit https://github.com/LuaLanes/lanes/commit/7b4f59c5ebc84e426e2876906b24d7dd73342f07

**Comment by benoit-germain** [comment]
All I can think of is that LuaJIT uses some bits of the light userdata value for internal purposes, and expects all provided values with those bits cleared. See ```uniquekey.h```. Maybe for some reason the masking is wrong or the detection incorrect...

**Comment by sonoro1234** [comment]
Yes,
https://github.com/LuaJIT/LuaJIT/issues/450#issuecomment-433659873

**Comment by sonoro1234** [comment]
That was the problem!!!
Thanks!!
