### ISSUE TITLE
How to control main thread 

### ISSUE THREAD

**Issue by MrLuer** [LuaLanes/lanes#183]
sub threads control by the main thread, but how to control the main thread?such as, if main thread sleep for 100s , at the 32s I want the main thread quit sleep，how to implement this

**Comment by sonoro1234** [comment]
lanes.sleep
Altought sleeping does not always makes sense when you are in a receive loop

**Comment by MrLuer** [comment]
@sonoro1234  thank you for your reply
I know timer,but how timer control or wakeup main thread?

**Comment by sonoro1234** [comment]
two posibilities:
-- main thread call lanes.sleep
-- main thread calls linda:receive (with or without timeout) waiting for a key that can be sent by a timer or by another thread.

**Comment by MrLuer** [comment]
@sonoro1234 
thank you very much, it helpful for me
