### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by TT-SW** [LuaLanes/lanes#193]
Why I can't execute the test code? It always report follow error:

➜  lanes-master cd tests 
➜  tests lua timer.lua
[1]    6458 segmentation fault  lua timer.lua
➜  tests lua
Lua 5.1.4  Copyright (C) 1994-2008 Lua.org, PUC-Rio
> require "lanes".configure()
[1]    6507 segmentation fault  lua
➜  tests require "lanes"
require:108: no matches found: gen(function(n) return 2*n end)
➜  tests lua
Lua 5.1.4  Copyright (C) 1994-2008 Lua.org, PUC-Rio
> require "lanes"
[1]    6543 segmentation fault  lua

What is the problem and how to solve it？ thanks~

**Comment by kdav5758** [comment]
I can't execute a simple program either. I can't even require the library without getting this:
```bash
$ lua
Lua 5.4.3  Copyright (C) 1994-2021 Lua.org, PUC-Rio
> local lanes = require "lanes".configure()
.../.luaver/luarocks/3.6.0_5.4/share/lua/5.4/lanes.lua:340: internal error: function dump failed.
stack traceback:
	[C]: in function 'lanes.core.lane_new'
	.../.luaver/luarocks/3.6.0_5.4/share/lua/5.4/lanes.lua:340: in function <...../.luaver/luarocks/3.6.0_5.4/share/lua/5.4/lanes.lua:338>
	...s5758/.luaver/luarocks/3.6.0_5.4/share/lua/5.4/lanes.lua:583: in function 'lanes.configure'
	stdin:1: in main chunk
	[C]: in ?
```

This is my Lua dev setup:
```bash
$ luaver current
==>  Current versions:
==>  lua-5.4.3
==>  luarocks-3.6.0
```

**Comment by TT-SW** [comment]
I have fixed this issue, there is a problem with my download package. and my colleague uses luarocks to install lanes, this problem is not occur. I copied his installed version lane.lua and lanes/ core.so, this problem is solved. thanks
