### ISSUE TITLE
Symbol not found: _LG_cancel_test

### ISSUE THREAD

**Issue by ValeryKV** [LuaLanes/lanes#200]
I installed lualanes via luarocks for lua 5.3 on macOS.
The call `local lanes = require "lanes".configure()` returns `dlopen(.luarocks/lib/lua/5.3/lanes/core.so, 6): Symbol not found: _LG_cancel_test`

**Comment by benoit-germain** [comment]
That's strange. This function is not part of Lane's public C API. It is declared in cancel.h, implemented in cancel.c, referenced in lanes.c.
Therefore, core.so could not even have been successfully linked if the function was missing.

**Comment by ValeryKV** [comment]
Possible luarocks issue. I will investigate.

**Comment by ValeryKV** [comment]
`lanes-3.15.1-0.rockspec` does not include `cancel.c` in `sources`.

**Comment by benoit-germain** [comment]
huh. cancel.c is two years old. I wonder how it escaped notice until now...

**Comment by benoit-germain** [comment]
rockspeck is now fixed and uploaded to luarocks.org.
