### ISSUE TITLE
Each treADS created increases memory and cannot be freed by lua_close(L) after completion   

### ISSUE THREAD

**Issue by xiaojieilli2016** [LuaLanes/lanes#201]
--luatest.lua
local lanes = require "lanes".configure( {with_timers=false} )
local linda = lanes.linda()
f = lanes.gen( function( n) return 2 * n end)
a1 = f( 1)  --Increase the memory
a 2= f( 1) --Increase the memory
a 3= f( 1) --Increase the memory

Call luatest. Lua using the Lua C API
  lua_State *L = luaL_newstate();
  luaL_openlibs(L);
  luaL_dofile(L, "luatest.lua");
  lua_close(L)

Memory cannot be freed without exiting the program. Why?

**Comment by benoit-germain** [comment]
I have done some tests by replacing the allocator and keeping trace of all allocations. As far as I can tell, Lanes itself and Lua don't leak anything. I do observe that the process memory usage increases when launching more states (tested under windows 10), but that does not seem to be related to Lanes or Lua, so there isn't really anything I can do about it.

That being said, in your particular example, memory growth is easily explained: each of your line
a1 = f(1)
creates a new global variable, which is garbage collected only when the state is closed. If you want to free the memory, you need to clear these globals, and wait for the garbage collector to do its work (or force a gc cycle manually).
