### ISSUE TITLE
In comparison.html, lanes.new() does not exist.

### ISSUE THREAD

**Issue by stuta** [LuaLanes/lanes#215]
Hello.

See http://lualanes.github.io/lanes/comparison.html

  local h1= lanes.gen("base", calculate)(1,2,3)
  local h2= lanes.new("base", calculate)(10,20,30)
  local h3= lanes.new("base", calculate)(100,200,300)

**Comment by benoit-germain** [comment]
I don't even remember ever touching this file, it's most probably a remainder of Asko's doing (the original creator of the module).
I take no responsibility in the continued accuracy of its contents. Fixing the code snippet is within my competence domain though :-).
I've looked in to history of lanes.lua, but I'm not really familiar with gitub's blame interface. Maybe there was a function lanes.new in the past, but I didn't find the change that removed it.
