### ISSUE TITLE
pthread_create error with GitHub Actions

### ISSUE THREAD

**Issue by QartemisT** [LuaLanes/lanes#218]
With the latest release of lanes, there's exceptions being thrown by lanes;

`src/threading.c 842: pthread_create() failed, 1 EPERM`

This was not occuring before this last release.

It appears that this commit broke this; <https://github.com/LuaLanes/lanes/commit/d73f4cee37b0a43edadf9709289798ee4bfccc0e>

**Comment by Mitalie** [comment]
Not specific to GitHub Actions, but happens generally on Linux when built without `-DLINUX_SCHED_RR` and run as non-root:

* The first time the table returned from `require "lanes"` is accessed, `lanesMeta.__index` calls `lanes.configure` which calls `gen( "*", { package= {}, priority = max_prio}, timer_body)()` in the first_time block.
* `max_prio` comes from `THREAD_PRIO_MAX`on the C side, defined as `(sudo ? +3 : 0)` so 0 for non-root.
* Before d73f4ce, `prio == 0` was treated as no-op in `THREAD_CREATE`. Now, it's different from `THREAD_PRIO_DEFAULT` and root permission is not confirmed when built without `-DLINUX_SCHED_RR`. `THREAD_CREATE` attempts to create a thread with policy `SCHED_RR`, priority 50, which fails for non-root.
