### ISSUE TITLE
Loading wximage on a separate thread and passing back the address 

### ISSUE THREAD

**Issue by fenix272** [LuaLanes/lanes#223]
I'm making a wxLua app and i have to populate the gui with images while scrolling. In wxLua(LuaJit + wxwidgets) i can clearly notice stutter, depending on the quality of the images. Is it possible to load those images in a separate lane or thread? A wxImage or a wxBitmap is created on the freestore afterl all, not on the stack, so it would only require passing a pointer(light userdata) back to the main thread. Is there a way to do that?

**Comment by fenix272** [comment]
Really? So i can create the  wxBitmap in a lane and then send back to the main thread? I''l try once i get back and let you know. Thank you for your answer

**Comment by fenix272** [comment]
I tried but i think i can't. 
```
local thr, err = lanes.gen("wx.*", createBitmaps) (fstart, fend, items)
if not err then
   drawBitmaps(items)
end

```
In the 'createBitmaps' routine i use the 'wx' namespace to create wxImage and wxBitmap. So i tried to  add it to lanes.gen('wx.*')
but it doesn'work. When a lane is created, it's not in another wxlua process? I compiled lanes using LuaJit. Is there a way to do that?

**Comment by fenix272** [comment]
I tried also to import the wx namespace within the lane like this
`local wx = require 'wx'`
but it doesn't work either

**Comment by fenix272** [comment]
I changed the  code to this
`
local thr, err = lanes.gen("", createBitmaps) (fstart, fend, items)
`
The error i get is 'Can't copy non-deep full userdata acros lanes'
But  'items' don't contain any userdata, don't understand

**Comment by benoit-germain** [comment]
When the function body is transferred over to the lane's state, the upvalues are transferred as well, and their own upvalues, and the metatables, etc. If a wx full userdata hides somewhere in there, you will have this failure.

Regarding lanes.gen("wx.*",...): this won't work. As per the documentation, this string can only list lua standard libraries, or "*" as a shortcut for all of them. Any non-standard library should be specified with lanes.gen({required{"module1", "module2", ...}, ...)

**Comment by fenix272** [comment]
Thank you for your answer.  I had not thought about the upvalues so i removed them and now i don't get that error anymore. I succeeded in loading the images in the lanes, but before transferring them back to the main thread i convert the data to strings with ffi.string, because i don't htink i can transfer back the userdata objects themselves(i couldn't even add the 'wx' module). Regarding the modules to add, first i did:
```
local ffi = require("ffi")
local freeimage = require 'freeimage'
lanes.register("ffi", ffi)
lanes.register("freeimage", freeimage)
```
and then when creating the new lanes
'''
lanes.gen('*', {required={'freeimage', 'ffi'}}, procScrolledItems) (fstart, fend, items)
'''
I just need those 2 modules, freeimage and ffi, with '*' i load also modules i don't need. I tried:
```
lanes.gen('package', {required={'freeimage', 'ffi'}}, procScrolledItems) (fstart, fend, items)
```
but i get the error 'module ffi not found' .
If i remove these 2 lines
```
lanes.register("ffi", ffi)
lanes.register("freeimage", freeimage)
```  
i get the strange errors such as 'function ffi/sizeof not found' and so on.
So how can i load just those 2 modules without all the others?

**Comment by benoit-germain** [comment]
Ah, in fact "ffi" is a special module, just like "jit". This works for me:
```
lanes=require"lanes".configure()
ffi = require("ffi")
lanes.register("ffi", ffi)
lanes.gen('package,ffi', function(...) local ffi = require"ffi" print(...) end) ("hello",ffi)
```
ffi=lanes.require("ffi") works too instead of require+lanes.register:
```
lanes=require"lanes".configure()
ffi = lanes.require("ffi")
lanes.gen('package,ffi', function(...) local ffi = require"ffi" print(...) end) ("hello",ffi)
```

**Comment by fenix272** [comment]
Thank you. It works!
