### ISSUE TITLE
Passing back Values to the main thread without ending the lane

### ISSUE THREAD

**Issue by fenix272** [LuaLanes/lanes#224]
I have this code
```
function startSrv(currDir, cb)
    local socket = require "socket"
    local srv = socket.bind("127.0.0.1", 7777)
    local ip, port = srv:getsockname()
    while true do 
        local client = srv:accept()
         -- client:settimeout(4.5)
        local str, err = client:receive('*a')
        if not err then
             client:send("HTTP/1.0 200 OK\r\n")
             local file = io.open(currDir..'SRVRESP.txt', 'a')
             file:write(str)
             file:close()
             if cb then cb(str) end
         end
        client:close()
    end
end
local launchSrv = lanes.gen('*', startSrv)
local lane, err = launchSrv(currDir, function(str) 
     local file = io.open(currDir..'SRVRESP.txt', 'a')
     file:write(str)
     file:close()
end)
```
It works, it writes the client data to the file but i would like to receive the data in the main thread without returning and in doing so closing the server. How can pass the data clients send to the server back to the main thread while still keeping the lane and the server alive? 
Is it possible to do so? Everything gets copied to the lane(even functions) so how can i write back to an array or calling a callback in the main thread like i can for example in pascal and all the major languages?

**Comment by benoit-germain** [comment]
Different lanes cannot do shared access to data, as it would require some kind of synchronization to preserve Lua state integrity All communications are performed with copies. If you want to communicate manually, use one or more linda objects.

**Comment by fenix272** [comment]
Thankyou for your answer. Yes i looked into linda but i don't know how to solve my problem. If i use lindas objects i have to set up a while loop in order to receive the data continuosly from the server while it's running, right? And that would block the main thread and defeat the whole purpose of using lanes. Or am i wrong here?

**Comment by benoit-germain** [comment]
```local lane, err = launchSrv(currDir, function(str) ...``` starts your lane.
This is a separate thread that runs in an infinite loop (```while true do ...  end```). It will keep running until the main thread terminates, which will forcefully kill it.
Until then, you can just have a polling loop in the main thread that sends/receives stuff using a linda.
Your worker could send whatever it wants in there, read it in the main thread, and you could issue a special message as well from the main thread when you want the worker to break out of the loop and terminate.

**Comment by fenix272** [comment]
I was reading on stackoverflow about a user who was asking the same question and the guy who answered(Michal Kottman) did not get it. This is the link: https://stackoverflow.com/questions/9572317/lua-lanes-communication-between-threads
 Or maybe i do'nt understand. In the lane thread i do:
```
function startSrv(linda)
    local socket = require "socket"
    local srv = socket.bind("127.0.0.1", 7777)
    local ip, port = srv:getsockname()
    while true do 
        local client = srv:accept()
         -- client:settimeout(4.5)
        local str, err = client:receive('*a')
        if not err then
             client:send("HTTP/1.0 200 OK\r\n")
             linda:send('k', str) --will this line block the server until the other end receive the data?
         end
        client:close()
    end
end
local launchSrv = lanes.gen('*', startSrv)
local linda = lanes.linda()
local lane, err = launchSrv(linda)
while true do --this loop will block the main thread, right?
  local str = linda:receive(2, 'k') --if timeout expires i lose the data?
end
```

**Comment by fenix272** [comment]
This line
```
local str = linda:receive(2, 'k')
```
will pause the main thread hence will block it,  right?
Just like this line
```
local client = srv:accept() --this line blocks the main thread and that's why i moved it  to a lane
```

**Comment by benoit-germain** [comment]
Luckily, you can specify a timeout when polling a linda for messages.

**Comment by fenix272** [comment]
Yes, i think i understand it now, with timeouts and polling i can make it work, thank you
