### ISSUE TITLE
Can't run tests with g++

### ISSUE THREAD

**Issue by Rx1513** [LuaLanes/lanes#229]
Add support for c++20.
![image](https://github.com/user-attachments/assets/80bbd621-eb5e-4ea2-b4ab-d2c71b371d50)

**Comment by benoit-germain** [comment]
src/Makefile contains
![image](https://github.com/user-attachments/assets/59a108c2-61ed-4436-b631-a168f3ee3d78)
So I suppose that's not what you are using to build Lanes? If through LuaRocks, I have yet to discover how to tell it to use c++20 in a compiler-agnostic way.

**Comment by Rx1513** [comment]
>So I suppose that's not what you are using to build Lanes? 
>
Yes ,I simply run ``make test`` in project's root directory

> ```alias g++='g++ -std=c++20'```
>
Didn't help

**Comment by benoit-germain** [comment]
I've just made changes, maybe it will be better. This works for me when default-building and installing Lua54 from the source tarball under mingw UCRT64.
