### ISSUE TITLE
Detection of windows condition variables implementation in the OS

### ISSUE THREAD

**Issue by overmersch** [LuaLanes/lanes#95]
Here are some thoughts, related to Issues #94, #65, #53 and compilation on windows. Some problems may arise in the current lanes versions :
- a binary compiled for vista or seven, with a compiler/SDK with WINVER >= 0x0600 probably won't run on XP due to lack of condition value related fonctions
- A binary compiled for XP would work on later versions with the pulse event implementation, but eventually with problems related in Issue #53
- As a consequence, if you want to support both OS with the same binaries, the choice is between pulse event implementation, or using pthreads for windows instead of native windows api
- The few #ifdef WINVER stuff leads to some non trivial machine/compiler/SDK dependant problems, as in Issues #84 and #65

IMHO ideally it would be better to have both implementations in the same binary, and let the system choose at runtime. Some time ago I had a look about OS detection, MSDN suggests an interesting solution here:
http://msdn.microsoft.com/en-us/library/windows/desktop/ms724832(v=vs.85).aspx

They suggest to test the presence of the needed features at runtime instead of detecting os version: basically, GetProcAdress of symbols like InitializeConditionVariable, etc in kernel32.dll would eventually return NULL on OSes without support of the feature. 
The idea would be to detect if the three or four needed fonctions are present, for example in the configure fonction, and then use them as function pointers (after having chosen one implementation or the other). This would impact only the lowest level (ie threading.[ch]).

It may not be trivial though, since this would be ok for functions but not for eventual structure typedefs. However, usually in this kind of API most of useful types are typedefs to pointers, so it may be possible to use the various MS opaque structures by just casting them to void*.

And as a side effect, this kind of solution would also remove all occurences of #ifdef WINVER in the code...

**Comment by benoit-germain** [comment]
The C++ implementation uses only std stuff now, so this has become a non-issue.
